/**
 * Responsive variant widths. These are generated by php/api/upload.php via
 * Imagick and consumed by src/lib/image-loader.ts.
 *
 * Changing this list requires regenerating existing images — upload.php writes
 * one file per width and nothing backfills. Keep in sync with:
 *   - next.config.ts       (images.deviceSizes)
 *   - php/api/upload.php   (VARIANT_WIDTHS)
 */
export const VARIANT_WIDTHS = [400, 800, 1200, 2000] as const;

export type VariantWidth = (typeof VARIANT_WIDTHS)[number];

/** Smallest generated variant at least as wide as `width`; largest otherwise. */
export function nearestVariant(width: number): VariantWidth {
  return (
    VARIANT_WIDTHS.find((w) => w >= width) ??
    VARIANT_WIDTHS[VARIANT_WIDTHS.length - 1]
  );
}

/**
 * `storagePath` is stored in Postgres without a width or extension
 * (e.g. "uploads/<project_id>/<uuid>"); each variant lives alongside it as
 * "<storagePath>-<width>.webp".
 */
export function variantUrl(storagePath: string, width: number): string {
  const base = storagePath.replace(/^\/+/, "");
  return `/${base}-${nearestVariant(width)}.webp`;
}
